services:
  # Mongodb service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db

  # Node api service
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
      target: ${TARGET}
    ports:
      # avoid conflict with ReactJS frontend default port.
      - 4000:3000
    environment:
      PORT: 3000
      MONGODB_URI: ${MONGODB_DOCKER_URI}
      DB_NAME: motorbike-shop-api
      COLLECTION_NAME: customers
    volumes: # TODO: Not sure - we have missing node_modules in local file system.
      - .:/usr/src/app
      # - /usr/src/app/node_modules
    depends_on:
      - mongo_db

volumes:
  mongo_data:
